name: Main compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: main-integration-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  compatibility:
    if: github.event_name == 'push' || github.head_ref == 'develop'
    uses: ./.github/workflows/compatibility.yml
